<a href="https://colab.research.google.com/github/lucylao/data_analytics/blob/main/Numpy_Classwork.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# np_city_with_state = np.array(['NYC','LA','Houston','Miami'], ['NY', 'CA', 'TX', 'FL'])
# np_city_with_state.ndim
# np_city_with_state

In [5]:
first_trial_cyclist = [10, 15, 17, 26]
second_trial_cyclist = [12, 11, 21, 24]

np_ftc = np.array(first_trial_cyclist)
np_stc = np.array(second_trial_cyclist)

np_ftc + np_stc


array([22, 26, 38, 50])

In [17]:
# two dimensional (two arrays) array tuple - ordered list

first_trial_cyclist = [10, 15, 17, 26]
second_trial_cyclist = [12, 11, 21, 24]
cyclist_time = np.array(([10, 15, 17, 26],[12, 11, 21,24]))
ftc_time = cyclist_time[0]
ftc_times = cyclist_time[0,0]
stc_time = cyclist_time[1]
stc_times = cyclist_time[1,0]

print(ftc_time)
print(ftc_times)
print(stc_time)
print(stc_times)

# to get ftc = 26
print(cyclist_time[0,3])
print(cyclist_time[::-1])
print(cyclist_time[-2,-3])

[10 15 17 26]
10
[12 11 21 24]
12
26
[[12 11 21 24]
 [10 15 17 26]]
15


In [20]:
# Boolean Arrays
# use criteria or set condition to select values

test_score = np.array([[81,71,57,63],[54,61,87,45]])
passing_score = test_score > 60
passing_score
test_score[passing_score]

array([81, 71, 63, 61, 87])

In [35]:
NYC_Borough = np.array(['Manhattan', 'Queens', 'Brooklyn', 'Staten Island', 'Bronx'])
NYC_Borough

Boroughs_NYC = NYC_Borough
Boroughs_NYC
Boroughs_in_NYC = Boroughs_NYC.view()
Boroughs_in_NYC
Boroughs_in_NYC is NYC_Borough
NYC_Borough is Boroughs_NYC
len(Boroughs_in_NYC)
Boroughs_in_NYC[3]


'Staten Island'

In [40]:
np_sqrt = np.sqrt([2,4,9,16,32])
np_sqrt

# from np import pi (will also work)
from numpy import pi
np.cos(0)
np.sin(pi/2)
np.cos(pi)
np.floor([1.5,1.6,2.7,3.3,1.1,-0.3,-1.4])


array([ 1.,  1.,  2.,  3.,  1., -1., -2.])

In [49]:
array_a = np.array([2, 3, 5, 9])
array_b = np.array([0.3, 0.3, 0.3, 0.3])

# multiply
array_a * array_b

#variable with scalar view
scalar_c = 4
array_a * scalar_c

array([ 8, 12, 20, 36])

In [50]:
# transpose (can only be applied to square matrix)
inverse_array = np.array([[10,20], [30, 40]])
np.linalg.inv(inverse_array)


array([[-0.2 ,  0.1 ],
       [ 0.15, -0.05]])

In [52]:
# trace (sum of diagonal elements)
trace_array = np.array([[10,20],[30,20]])
np.trace(trace_array)

30